baseurl = "/"
defaultContentLanguage = "ua"
enableRobotsTXT = true

[languages]
  [languages.ua]
    weight = 1
    languageName = "UA"
    title = "Meine Hugo-Seite"
    # Другие настройки для украинского
  [languages.en]
    weight = 2
    languageName = "ENG"
    title = "My Hugo Site"
    # Другие настройки для английского

  

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]

[permalinks]
  blog = ':title/'

[imaging]
# See https://github.com/disintegration/imaging
  resampleFilter = "Lanczos"
  quality = 100
